version: '3'

services:
  db:
    image: postgres
    ports:
      - '4000:5432'
  web:
    image: learning_platform
    command: python local.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
