# Generated by Django 2.0.2 on 2018-10-12 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('is_master', models.BooleanField(default=False)),
                ('termination_type', models.CharField(choices=[('BR', 'BREAK'), ('NOR', 'NORMAL')], max_length=5, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('TODO', 'TODO'), ('INP', 'IN_PROGRESS'), ('CP', 'COMPLETED')], default='TODO', max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('eta', models.DateTimeField(default=datetime.datetime(2018, 10, 12, 16, 2, 14, 364745, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='studyobjects.Assessment')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='studyobjects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
