# Generated by Django 2.0.2 on 2018-10-12 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studyobjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='eta',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 12, 1, 45, 574227, tzinfo=utc)),
        ),
    ]
