# Generated by Django 2.0.2 on 2018-10-12 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyobjects', '0003_auto_20181012_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='eta',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 21, 47, 42, 13389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
