# Generated by Django 2.0.2 on 2018-10-13 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('studyobjects', '0004_auto_20181012_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_clarified', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyobjects.Assessment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studyobjects.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TeamMembership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubtsClarified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('clarified_response', models.TextField(blank=True, null=True)),
                ('is_clarified', models.BooleanField(default=False)),
                ('cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.TeamMembership')),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyobjects.Doubts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='eta',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 6, 18, 19, 551412, tzinfo=utc)),
        ),
    ]
