# Generated by Django 2.0.2 on 2018-10-12 15:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('identity', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=20, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('identity', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('access_token', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_update', models.DateTimeField(auto_now=True)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='team_memberships', to='auth.Group')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.PlatformUser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team')),
            ],
        ),
        migrations.AddField(
            model_name='platformuser',
            name='teams',
            field=models.ManyToManyField(related_name='platform_users', through='user.TeamMembership', to='user.Team'),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('platform_user', 'team')},
        ),
    ]
